version: '3'
services:
  bot:
    build:
      context: .
    #image: "horhik/instagram2fedi:latest"
    volumes:
      - ${HOME}/.config/instaloader:/root/.config/instaloader
      - ./config:/app/config
    environment:
      - YOUR_CONTAINER_NAME=instagram2fedi
      - I2M_INSTAGRAM_USER= #<instagram username to be fetched>
      - I2M_INSTANCE= #<Mastodon or Pixelfed instance> Leave blank if you use src/create_credentials.py.
      - I2M_TOKEN= #<SECRET MASTODON TOKEN filename> Leave blank if you use src/create_credentials.py.
      - I2M_CHECK_INTERVAL=3600 #1 hour
      - I2M_POST_INTERVAL=3600 #1 hour
      - I2M_USE_MASTODON=4 #max carouse    - is 4, if there's no limit set to -1
      - I2M_FETCH_COUNT=5 # how many instagram posts to fetch per check_interval
      - I2M_USER_NAME= #<Your instagram login name>
      - I2M_USER_PASSWORD= #<Your instagram password> Not needed if ~/.config/instaloader/session-${I2M_USER_NAME} exists.
